package com.servebeer.please.smartcharger.manager;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class DifferentialChargingManagerStatus {

    // number of Watts of power generated by the SolarMax Array
    private int generatedPower = 0;

    // number of Watts of power to "reserve" for other usage.
    private int powerBuffer = 2000;

    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date updatedAt = new Date();
    private boolean connected = false;
    private boolean charging = false;
    private boolean LocatedAtSolarmaxArray = false;
    private int teslaPowerDraw = 0;
    private int batteryLevel = 0;
    private int chargeLimit = 0;

    public int getGeneratedPower() {
        return generatedPower;
    }

    public void setGeneratedPower(int generatedPower) {
        this.generatedPower = generatedPower;
    }

    public int getPowerBuffer() {
        return powerBuffer;
    }

    public void setPowerBuffer(int powerBuffer) {
        this.powerBuffer = powerBuffer;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public int getTeslaPowerDraw() {
        return teslaPowerDraw;
    }

    public void setTeslaPowerDraw(int teslaPowerDraw) {
        this.teslaPowerDraw = teslaPowerDraw;
    }

    public int getBatteryLevel() {
        return batteryLevel;
    }

    public void setBatteryLevel(int batteryLevel) {
        this.batteryLevel = batteryLevel;
    }

    public int getChargeLimit() {
        return chargeLimit;
    }

    public void setChargeLimit(int chargeLimit) {
        this.chargeLimit = chargeLimit;
    }

    public boolean isCharging() {
        return charging;
    }

    public void setCharging(boolean charging) {
        this.charging = charging;
    }

    public boolean isConnected() { return connected; }

    public void setConnected(boolean connected) {
        this.connected = connected;
    }

    public boolean isLocatedAtSolarmaxArray() {
        return LocatedAtSolarmaxArray;
    }

    public void setLocatedAtSolarmaxArray(boolean locatedAtSolarmaxArray) {
        LocatedAtSolarmaxArray = locatedAtSolarmaxArray;
    }

}
