package com.servebeer.please.smartcharger.manager;


import com.servebeer.please.solarmax.array.ArrayManager;
import com.servebeer.please.tesla_client.GpsLocation;

public class SolarmaxArrayCommunicator {

    private static final GpsLocation gpsLocation = new GpsLocation(Float.valueOf("46.745726"), Float.valueOf("7.647738"));

    /**
     * @return the Watts of power currently being generated by the array of SolarMax Devices
     */
    int getCurrentlyGeneratedPower() {
        return ArrayManager.getCurrentlyGeneratedPower();
    }

    public static GpsLocation getGpsLocation() {
        return gpsLocation;
    }
}
